### ISSUE TITLE
Ubuntu 部署 FoundryVTT 教程

### ISSUE THREAD

**Issue by OniSaku1024** [fvtt-cn/fvtt-cn.github.io#8]
现在使用wget下载fvtt的linux版时，下载后的文件名需要手动重命名。mv [option] 原路径 目标路径

**Comment by hmqgg** [comment]
没太理解什么问题，下载下来的应该本来就是 foundryvtt-0.7.9.zip 这样的文件，默认应该也都是在 ~ 下部署的？
如果有更多问题，期望提交 PR 来修改。

**Comment by OniSaku1024** [comment]
我下载下来的文件名格式是foundryvtt-0.7.9.zip后面加了一大串字符串，就是网站提供的那个下载签名的字符串。复制链接的方法是从网站上点那个锁链的小图标。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fvtt-cn/fvtt-cn.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 下午5:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fvtt-cn/fvtt-cn.github.io] Ubuntu 部署 FoundryVTT 教程 (#8)





 
没太理解什么问题，下载下来的应该本来就是 foundryvtt-0.7.9.zip 这样的文件，默认应该也都是在 ~ 下部署的？
 如果有更多问题，期望提交 PR 来修改。
